"""Pandera schemas for ratio rapport tables (VHE and complex level)."""

from __future__ import annotations

import pandas as pd
import pandera.pandas as pa
from pandera.typing.pandas import Series


class RatioRapportVheSchema(pa.DataFrameModel):
    """Schema for tms.ratio_rapport_vhe (71 cols) — financial ratios per VHE."""

    vhe_nr: Series[str] = pa.Field(alias="VHE-nr")
    waarderingscomplex: Series[str] = pa.Field(alias="Waarderingscomplex", nullable=True)
    complexnaam: Series[str] = pa.Field(alias="Complexnaam", nullable=True)
    deelportefeuille: Series[str] = pa.Field(alias="Deelportefeuille", nullable=True)
    adres: Series[str] = pa.Field(alias="Adres", nullable=True)
    postcode: Series[str] = pa.Field(alias="Postcode", nullable=True)
    scenario: Series[str] = pa.Field(alias="Scenario", nullable=True)
    model: Series[str] = pa.Field(alias="Model", nullable=True)
    bouwjaar: Series[float] = pa.Field(alias="Bouwjaar", nullable=True, coerce=True)
    handboektype: Series[str] = pa.Field(alias="Handboektype", nullable=True)
    classificatie: Series[str] = pa.Field(alias="Classificatie", nullable=True)
    netto_marktwaarde: Series[float] = pa.Field(alias="Netto Marktwaarde", nullable=True, coerce=True)
    netto_marktwaarde_de: Series[float] = pa.Field(alias="Netto marktwaarde (DE)", nullable=True, coerce=True)
    netto_marktwaarde_up: Series[float] = pa.Field(alias="Netto marktwaarde (UP)", nullable=True, coerce=True)
    bruto_marktwaarde_de: Series[float] = pa.Field(alias="Bruto marktwaarde (DE)", nullable=True, coerce=True)
    bruto_marktwaarde_up: Series[float] = pa.Field(alias="Bruto marktwaarde (UP)", nullable=True, coerce=True)
    marktwaarde_de_up: Series[float] = pa.Field(alias="Marktwaarde DE / UP", nullable=True, coerce=True)
    marktwaarde_excl_correcties: Series[float] = pa.Field(alias="Marktwaarde excl. correcties", nullable=True, coerce=True)
    correctie_achterstallig_onderhoud: Series[float] = pa.Field(alias="Correctie achterstallig onderhoud", nullable=True, coerce=True)
    correctie_erfpacht: Series[float] = pa.Field(alias="Correctie erfpacht", nullable=True, coerce=True)
    oppervlakte_gbo_vvo: Series[float] = pa.Field(alias="Oppervlakte GBO of VVO", nullable=True, coerce=True)
    oppervlakte_bvo: Series[float] = pa.Field(alias="Oppervlakte BVO", nullable=True, coerce=True)
    marktwaarde_per_m2_gbo_vvo: Series[float] = pa.Field(alias="Marktwaarde per m² GBO of VVO", nullable=True, coerce=True)
    woz_waarde: Series[float] = pa.Field(alias="WOZ-waarde", nullable=True, coerce=True)
    leegwaarde: Series[float] = pa.Field(alias="Leegwaarde", nullable=True, coerce=True)
    huur_leegwaarde: Series[float] = pa.Field(alias="Huur / Leegwaarde", nullable=True, coerce=True)
    theoretische_huurinkomsten_leegwaarde: Series[float] = pa.Field(alias="Theoretische huurinkomsten / Leegwaarde", nullable=True, coerce=True)
    eindwaarde_leegwaarde: Series[float] = pa.Field(alias="Eindwaarde / Leegwaarde", nullable=True, coerce=True)
    marktwaarde_woz: Series[float] = pa.Field(alias="Marktwaarde / WOZ-waarde", nullable=True, coerce=True)
    marktwaarde_leegwaarde: Series[float] = pa.Field(alias="Marktwaarde / Leegwaarde", nullable=True, coerce=True)
    leegwaarde_per_m2_gbo_vvo: Series[float] = pa.Field(alias="Leegwaarde per m² GBO of VVO", nullable=True, coerce=True)
    onderhoud: Series[float] = pa.Field(alias="Onderhoud", nullable=True, coerce=True)
    onderhoud_per_m2_gbo_bvo: Series[float] = pa.Field(alias="Onderhoud per m² GBO of BVO", nullable=True, coerce=True)
    bar_kk_contracthuur: Series[float] = pa.Field(alias="BAR kk (contracthuur)", nullable=True, coerce=True)
    nar_kk_contracthuur: Series[float] = pa.Field(alias="NAR kk (contracthuur)", nullable=True, coerce=True)
    kf_kk_contracthuur: Series[float] = pa.Field(alias="KF kk (contracthuur)", nullable=True, coerce=True)
    kf_kk_markthuur: Series[float] = pa.Field(alias="KF kk (markthuur)", nullable=True, coerce=True)
    kf_kk_theoretische_huur: Series[float] = pa.Field(alias="KF kk (theoretische huur)", nullable=True, coerce=True)
    kf_kk_excl_correcties_contracthuur: Series[float] = pa.Field(alias="KF kk excl. correcties (contracthuur)", nullable=True, coerce=True)
    exploitatiekosten_de_per_m2_gbo_bvo: Series[float] = pa.Field(alias="Exploitatiekosten (DE) per m² GBO of BVO", nullable=True, coerce=True)
    contracthuur_per_maand: Series[float] = pa.Field(alias="Contracthuur per maand", nullable=True, coerce=True)
    potentiele_huur_per_maand: Series[float] = pa.Field(alias="Potentiële huur per maand", nullable=True, coerce=True)
    theoretische_huurinkomsten_per_maand: Series[float] = pa.Field(alias="Theoretische huurinkomsten per maand", nullable=True, coerce=True)
    exploitatiekosten_de: Series[float] = pa.Field(alias="Exploitatiekosten (DE)", nullable=True, coerce=True)
    exploitatiekosten_de_contracthuur_per_jaar: Series[float] = pa.Field(alias="Exploitatiekosten (DE) / contracthuur per jaar", nullable=True, coerce=True)
    contracthuur_jaar_per_m2_gbo_vvo: Series[float] = pa.Field(alias="Contracthuur (jaar) per m² GBO of VVO", nullable=True, coerce=True)
    markthuur_per_maand: Series[float] = pa.Field(alias="Markthuur per maand", nullable=True, coerce=True)
    markthuur_jaar_per_m2_gbo_vvo: Series[float] = pa.Field(alias="Markthuur (jaar) per m² GBO of VVO", nullable=True, coerce=True)
    zelfstandig: Series[str] = pa.Field(alias="Zelfstandig", nullable=True)
    gereguleerd: Series[str] = pa.Field(alias="Gereguleerd", nullable=True)
    leegstand: Series[str] = pa.Field(alias="Leegstand", nullable=True)
    maximale_huur_per_maand: Series[float] = pa.Field(alias="Maximale huur per maand", nullable=True, coerce=True)
    mutatiegraad_de: Series[float] = pa.Field(alias="Mutatiegraad DE", nullable=True, coerce=True)
    mutatiegraad_up: Series[float] = pa.Field(alias="Mutatiegraad UP", nullable=True, coerce=True)
    energielabel: Series[str] = pa.Field(alias="Energielabel", nullable=True)
    disconteringsvoet: Series[float] = pa.Field(alias="Disconteringsvoet", nullable=True, coerce=True)
    disconteringsvoet_de: Series[float] = pa.Field(alias="Disconteringsvoet DE", nullable=True, coerce=True)
    disconteringsvoet_up: Series[float] = pa.Field(alias="Disconteringsvoet UP", nullable=True, coerce=True)
    exit_yield_de: Series[float] = pa.Field(alias="Exit yield DE", nullable=True, coerce=True)
    exit_yield_up: Series[float] = pa.Field(alias="Exit yield UP", nullable=True, coerce=True)
    huur_leegwaarde_jaar_15_de: Series[float] = pa.Field(alias="Huur / Leegwaarde jaar 15 DE", nullable=True, coerce=True)
    huur_leegwaarde_jaar_15_up: Series[float] = pa.Field(alias="Huur / Leegwaarde jaar 15 UP", nullable=True, coerce=True)
    markthuur_jaar_15: Series[float] = pa.Field(alias="Markthuur jaar 15", nullable=True, coerce=True)
    contracthuur_jaar_15: Series[float] = pa.Field(alias="Contracthuur jaar 15", nullable=True, coerce=True)
    contante_waarde_contract: Series[float] = pa.Field(alias="Contante waarde contract", nullable=True, coerce=True)
    ingangsdatum_contract: Series[pd.Timestamp] = pa.Field(alias="Ingangsdatum contract", nullable=True)
    looptijd_in_maanden: Series[float] = pa.Field(alias="Looptijd in maanden", nullable=True, coerce=True)
    nieuw_contract: Series[str] = pa.Field(alias="Nieuw contract", nullable=True)

    corporatie: Series[str] = pa.Field(alias="Corporatie")
    jaar: Series[int] = pa.Field(alias="Jaar", coerce=True)
    peildatum: Series[pd.Timestamp] = pa.Field(alias="Peildatum")

    class Config:
        strict = False
        coerce = True


class RatioRapportComplexSchema(pa.DataFrameModel):
    """Schema for tms.ratio_rapport_complex (69 cols) — financial ratios per complex."""

    waarderingscomplex: Series[str] = pa.Field(alias="Waarderingscomplex")
    complexnaam: Series[str] = pa.Field(alias="Complexnaam", nullable=True)
    deelportefeuille: Series[str] = pa.Field(alias="Deelportefeuille", nullable=True)
    straatnaam: Series[str] = pa.Field(alias="Straatnaam", nullable=True)
    scenario: Series[str] = pa.Field(alias="Scenario", nullable=True)
    model: Series[str] = pa.Field(alias="Model", nullable=True)
    aantal_vhes: Series[float] = pa.Field(alias="Aantal VHE's", nullable=True, coerce=True)
    aantal_vhes_leegstaand: Series[float] = pa.Field(alias="Aantal VHE's leegstaand", nullable=True, coerce=True)
    percentage_leegstaand: Series[float] = pa.Field(alias="Percentage leegstaand in complex", nullable=True, coerce=True)
    netto_marktwaarde: Series[float] = pa.Field(alias="Netto Marktwaarde", nullable=True, coerce=True)
    gemiddelde_marktwaarde: Series[float] = pa.Field(alias="Gemiddelde marktwaarde", nullable=True, coerce=True)
    netto_marktwaarde_de: Series[float] = pa.Field(alias="Netto marktwaarde (DE)", nullable=True, coerce=True)
    netto_marktwaarde_up: Series[float] = pa.Field(alias="Netto marktwaarde (UP)", nullable=True, coerce=True)
    bruto_marktwaarde_de: Series[float] = pa.Field(alias="Bruto marktwaarde (DE)", nullable=True, coerce=True)
    bruto_marktwaarde_up: Series[float] = pa.Field(alias="Bruto marktwaarde (UP)", nullable=True, coerce=True)
    marktwaarde_de_up: Series[float] = pa.Field(alias="Marktwaarde DE / UP", nullable=True, coerce=True)
    marktwaarde_excl_correcties: Series[float] = pa.Field(alias="Marktwaarde excl. correcties", nullable=True, coerce=True)
    correctie_achterstallig_onderhoud: Series[float] = pa.Field(alias="Correctie achterstallig onderhoud", nullable=True, coerce=True)
    correctie_erfpacht: Series[float] = pa.Field(alias="Correctie erfpacht", nullable=True, coerce=True)
    oppervlakte_gbo_vvo: Series[float] = pa.Field(alias="Oppervlakte GBO of VVO", nullable=True, coerce=True)
    oppervlakte_gbo_vvo_per_vhe: Series[float] = pa.Field(alias="Oppervlakte GBO of VVO per VHE", nullable=True, coerce=True)
    oppervlakte_bvo: Series[float] = pa.Field(alias="Oppervlakte BVO", nullable=True, coerce=True)
    marktwaarde_per_m2_gbo_vvo: Series[float] = pa.Field(alias="Marktwaarde per m² GBO of VVO", nullable=True, coerce=True)
    woz_waarde_per_vhe: Series[float] = pa.Field(alias="WOZ-waarde per VHE", nullable=True, coerce=True)
    leegwaarde: Series[float] = pa.Field(alias="Leegwaarde", nullable=True, coerce=True)
    leegwaarde_per_vhe: Series[float] = pa.Field(alias="Leegwaarde per VHE", nullable=True, coerce=True)
    huur_leegwaarde: Series[float] = pa.Field(alias="Huur / Leegwaarde", nullable=True, coerce=True)
    theoretische_huurinkomsten_leegwaarde: Series[float] = pa.Field(alias="Theoretische huurinkomsten / Leegwaarde", nullable=True, coerce=True)
    eindwaarde_leegwaarde: Series[float] = pa.Field(alias="Eindwaarde / Leegwaarde", nullable=True, coerce=True)
    marktwaarde_woz: Series[float] = pa.Field(alias="Marktwaarde / WOZ-waarde", nullable=True, coerce=True)
    marktwaarde_leegwaarde: Series[float] = pa.Field(alias="Marktwaarde / Leegwaarde", nullable=True, coerce=True)
    leegwaarde_per_m2_gbo_vvo: Series[float] = pa.Field(alias="Leegwaarde per m² GBO of VVO", nullable=True, coerce=True)
    onderhoud_per_vhe: Series[float] = pa.Field(alias="Onderhoud per VHE", nullable=True, coerce=True)
    onderhoud_per_m2_gbo_bvo: Series[float] = pa.Field(alias="Onderhoud per m² GBO of BVO", nullable=True, coerce=True)
    bar_kk_contracthuur: Series[float] = pa.Field(alias="BAR kk (contracthuur)", nullable=True, coerce=True)
    nar_kk_contracthuur: Series[float] = pa.Field(alias="NAR kk (contracthuur)", nullable=True, coerce=True)
    kf_kk_contracthuur: Series[float] = pa.Field(alias="KF kk (contracthuur)", nullable=True, coerce=True)
    kf_kk_markthuur: Series[float] = pa.Field(alias="KF kk (markthuur)", nullable=True, coerce=True)
    kf_kk_theoretische_huur: Series[float] = pa.Field(alias="KF kk (theoretische huur)", nullable=True, coerce=True)
    kf_kk_excl_correcties_contracthuur: Series[float] = pa.Field(alias="KF kk excl. correcties (contracthuur)", nullable=True, coerce=True)
    exploitatiekosten_de_per_m2_gbo_bvo: Series[float] = pa.Field(alias="Exploitatiekosten (DE) per m² GBO of BVO", nullable=True, coerce=True)
    contracthuur_per_maand: Series[float] = pa.Field(alias="Contracthuur per maand", nullable=True, coerce=True)
    potentiele_huur_per_maand: Series[float] = pa.Field(alias="Potentiële huur per maand", nullable=True, coerce=True)
    theoretische_huurinkomsten_per_maand: Series[float] = pa.Field(alias="Theoretische huurinkomsten per maand", nullable=True, coerce=True)
    exploitatiekosten_de: Series[float] = pa.Field(alias="Exploitatiekosten (DE)", nullable=True, coerce=True)
    exploitatiekosten_de_contracthuur_per_jaar: Series[float] = pa.Field(alias="Exploitatiekosten (DE) / contracthuur per jaar", nullable=True, coerce=True)
    contracthuur_jaar_per_m2_gbo_vvo: Series[float] = pa.Field(alias="Contracthuur (jaar) per m² GBO of VVO", nullable=True, coerce=True)
    markthuur_per_maand: Series[float] = pa.Field(alias="Markthuur per maand", nullable=True, coerce=True)
    markthuur_jaar_per_m2_gbo_vvo: Series[float] = pa.Field(alias="Markthuur (jaar) per m² GBO of VVO", nullable=True, coerce=True)
    maximale_huur_per_maand: Series[float] = pa.Field(alias="Maximale huur per maand", nullable=True, coerce=True)
    exploitatieverplichting: Series[str] = pa.Field(alias="Exploitatieverplichting", nullable=True)
    mutatiegraad_de: Series[float] = pa.Field(alias="Mutatiegraad DE", nullable=True, coerce=True)
    mutatiegraad_up: Series[float] = pa.Field(alias="Mutatiegraad UP", nullable=True, coerce=True)
    energielabel: Series[str] = pa.Field(alias="Energielabel", nullable=True)
    disconteringsvoet: Series[float] = pa.Field(alias="Disconteringsvoet", nullable=True, coerce=True)
    disconteringsvoet_de: Series[float] = pa.Field(alias="Disconteringsvoet DE", nullable=True, coerce=True)
    disconteringsvoet_up: Series[float] = pa.Field(alias="Disconteringsvoet UP", nullable=True, coerce=True)
    exit_yield: Series[float] = pa.Field(alias="Exit yield", nullable=True, coerce=True)
    exit_yield_de: Series[float] = pa.Field(alias="Exit yield DE", nullable=True, coerce=True)
    exit_yield_up: Series[float] = pa.Field(alias="Exit yield UP", nullable=True, coerce=True)
    huur_leegwaarde_jaar_15_de: Series[float] = pa.Field(alias="Huur / Leegwaarde jaar 15 DE", nullable=True, coerce=True)
    huur_leegwaarde_jaar_15_up: Series[float] = pa.Field(alias="Huur / Leegwaarde jaar 15 UP", nullable=True, coerce=True)
    markthuur_jaar_15: Series[float] = pa.Field(alias="Markthuur jaar 15", nullable=True, coerce=True)
    contracthuur_jaar_15: Series[float] = pa.Field(alias="Contracthuur jaar 15", nullable=True, coerce=True)
    contante_waarde_contract: Series[float] = pa.Field(alias="Contante waarde contract", nullable=True, coerce=True)
    wault: Series[float] = pa.Field(alias="WAULT", nullable=True, coerce=True)

    corporatie: Series[str] = pa.Field(alias="Corporatie")
    jaar: Series[int] = pa.Field(alias="Jaar", coerce=True)
    peildatum: Series[pd.Timestamp] = pa.Field(alias="Peildatum")

    class Config:
        strict = False
        coerce = True
