"""Pandera schemas for market value parameter tables (VHE-level and complex-level)."""

from __future__ import annotations

import pandas as pd
import pandera.pandas as pa
from pandera.typing.pandas import Series


class VheParamWoningenParkerenSchema(pa.DataFrameModel):
    """Schema for tms.market_value_parameters_vhe_param_woningen_parkeren."""

    vhe_nr: Series[str] = pa.Field(alias="VHE-nr")
    adres: Series[str] = pa.Field(alias="Adres", nullable=True)
    complexcode: Series[str] = pa.Field(alias="Complexcode", nullable=True)
    complexnaam: Series[str] = pa.Field(alias="Complexnaam", nullable=True)
    waarderingsmodel: Series[str] = pa.Field(alias="Waarderingsmodel", nullable=True)
    deelportefeuille: Series[str] = pa.Field(alias="Deelportefeuille", nullable=True)
    segment_huurregime: Series[str] = pa.Field(alias="Segment huurregime", nullable=True)
    classificatie: Series[str] = pa.Field(alias="Classificatie", nullable=True)
    markthuur_mh: Series[str] = pa.Field(alias="Markthuur (MH)", nullable=True)
    mh_waarde: Series[float] = pa.Field(alias="MH waarde", nullable=True, coerce=True)
    leegwaarde_lw: Series[str] = pa.Field(alias="Leegwaarde (LW)", nullable=True)
    lw_waarde: Series[float] = pa.Field(alias="LW waarde", nullable=True, coerce=True)
    epv: Series[str] = pa.Field(alias="EPV", nullable=True)
    huurbeklemming: Series[str] = pa.Field(alias="Huurbeklemming", nullable=True)
    erfpacht_ep: Series[str] = pa.Field(alias="Erfpacht (EP)", nullable=True)
    ep_waardecorrectie_doorexploiteren: Series[float] = pa.Field(alias="EP waardecorrectie doorexploiteren", nullable=True, coerce=True)
    ep_waardecorrectie_uitponden: Series[float] = pa.Field(alias="EP waardecorrectie uitponden", nullable=True, coerce=True)
    ep_suppletie_bij_verkoop: Series[float] = pa.Field(alias="EP suppletie bij verkoop", nullable=True, coerce=True)
    ep_jaarlijks_indexeren: Series[str] = pa.Field(alias="EP jaarlijks indexeren", nullable=True)
    ep_doorexploiteren_jaar_1: Series[float] = pa.Field(alias="EP doorexploiteren jaar 1", nullable=True, coerce=True)
    ep_doorexploiteren_jaar_2: Series[float] = pa.Field(alias="EP doorexploiteren jaar 2", nullable=True, coerce=True)
    ep_doorexploiteren_jaar_3: Series[float] = pa.Field(alias="EP doorexploiteren jaar 3", nullable=True, coerce=True)
    ep_doorexploiteren_jaar_4: Series[float] = pa.Field(alias="EP doorexploiteren jaar 4", nullable=True, coerce=True)
    ep_doorexploiteren_jaar_5: Series[float] = pa.Field(alias="EP doorexploiteren jaar 5", nullable=True, coerce=True)
    ep_doorexploiteren_jaar_6: Series[float] = pa.Field(alias="EP doorexploiteren jaar 6", nullable=True, coerce=True)
    ep_doorexploiteren_jaar_7: Series[float] = pa.Field(alias="EP doorexploiteren jaar 7", nullable=True, coerce=True)
    ep_doorexploiteren_jaar_8: Series[float] = pa.Field(alias="EP doorexploiteren jaar 8", nullable=True, coerce=True)
    ep_doorexploiteren_jaar_9: Series[float] = pa.Field(alias="EP doorexploiteren jaar 9", nullable=True, coerce=True)
    ep_doorexploiteren_jaar_10: Series[float] = pa.Field(alias="EP doorexploiteren jaar 10", nullable=True, coerce=True)
    ep_doorexploiteren_jaar_11: Series[float] = pa.Field(alias="EP doorexploiteren jaar 11", nullable=True, coerce=True)
    ep_doorexploiteren_jaar_12: Series[float] = pa.Field(alias="EP doorexploiteren jaar 12", nullable=True, coerce=True)
    ep_doorexploiteren_jaar_13: Series[float] = pa.Field(alias="EP doorexploiteren jaar 13", nullable=True, coerce=True)
    ep_doorexploiteren_jaar_14: Series[float] = pa.Field(alias="EP doorexploiteren jaar 14", nullable=True, coerce=True)
    ep_doorexploiteren_jaar_15: Series[float] = pa.Field(alias="EP doorexploiteren jaar 15", nullable=True, coerce=True)
    ep_uitponden_jaar_1: Series[float] = pa.Field(alias="EP uitponden jaar 1", nullable=True, coerce=True)
    ep_uitponden_jaar_2: Series[float] = pa.Field(alias="EP uitponden jaar 2", nullable=True, coerce=True)
    ep_uitponden_jaar_3: Series[float] = pa.Field(alias="EP uitponden jaar 3", nullable=True, coerce=True)
    ep_uitponden_jaar_4: Series[float] = pa.Field(alias="EP uitponden jaar 4", nullable=True, coerce=True)
    ep_uitponden_jaar_5: Series[float] = pa.Field(alias="EP uitponden jaar 5", nullable=True, coerce=True)
    ep_uitponden_jaar_6: Series[float] = pa.Field(alias="EP uitponden jaar 6", nullable=True, coerce=True)
    ep_uitponden_jaar_7: Series[float] = pa.Field(alias="EP uitponden jaar 7", nullable=True, coerce=True)
    ep_uitponden_jaar_8: Series[float] = pa.Field(alias="EP uitponden jaar 8", nullable=True, coerce=True)
    ep_uitponden_jaar_9: Series[float] = pa.Field(alias="EP uitponden jaar 9", nullable=True, coerce=True)
    ep_uitponden_jaar_10: Series[float] = pa.Field(alias="EP uitponden jaar 10", nullable=True, coerce=True)
    ep_uitponden_jaar_11: Series[float] = pa.Field(alias="EP uitponden jaar 11", nullable=True, coerce=True)
    ep_uitponden_jaar_12: Series[float] = pa.Field(alias="EP uitponden jaar 12", nullable=True, coerce=True)
    ep_uitponden_jaar_13: Series[float] = pa.Field(alias="EP uitponden jaar 13", nullable=True, coerce=True)
    ep_uitponden_jaar_14: Series[float] = pa.Field(alias="EP uitponden jaar 14", nullable=True, coerce=True)
    ep_uitponden_jaar_15: Series[float] = pa.Field(alias="EP uitponden jaar 15", nullable=True, coerce=True)
    extra_onderhoud_eo: Series[str] = pa.Field(alias="Extra onderhoud (EO)", nullable=True)
    eo_doorexploiteren: Series[float] = pa.Field(alias="EO doorexploiteren", nullable=True, coerce=True)
    eo_uitponden: Series[float] = pa.Field(alias="EO uitponden", nullable=True, coerce=True)
    huurstijging_hs: Series[str] = pa.Field(alias="Huurstijging (HS)", nullable=True)
    hs_jaar_1: Series[float] = pa.Field(alias="HS jaar 1", nullable=True, coerce=True)
    hs_jaar_2: Series[float] = pa.Field(alias="HS jaar 2", nullable=True, coerce=True)
    hs_jaar_3: Series[float] = pa.Field(alias="HS jaar 3", nullable=True, coerce=True)
    hs_jaar_4: Series[float] = pa.Field(alias="HS jaar 4", nullable=True, coerce=True)
    hs_jaar_5: Series[float] = pa.Field(alias="HS jaar 5", nullable=True, coerce=True)
    hs_jaar_6: Series[float] = pa.Field(alias="HS jaar 6", nullable=True, coerce=True)
    huurstijging_opslag_hso: Series[str] = pa.Field(alias="Huurstijging opslag (HSO)", nullable=True)
    hso_jaar_1: Series[float] = pa.Field(alias="HSO jaar 1", nullable=True, coerce=True)
    hso_jaar_2: Series[float] = pa.Field(alias="HSO jaar 2", nullable=True, coerce=True)
    hso_jaar_3: Series[float] = pa.Field(alias="HSO jaar 3", nullable=True, coerce=True)
    hso_jaar_4: Series[float] = pa.Field(alias="HSO jaar 4", nullable=True, coerce=True)
    hso_jaar_5: Series[float] = pa.Field(alias="HSO jaar 5", nullable=True, coerce=True)
    hso_jaar_6: Series[float] = pa.Field(alias="HSO jaar 6", nullable=True, coerce=True)
    servicekosten_eigen_rekening_sk: Series[str] = pa.Field(alias="Servicekosten eigen rekening (SK)", nullable=True)
    sk_bedrag: Series[float] = pa.Field(alias="SK bedrag", nullable=True, coerce=True)

    corporatie: Series[str] = pa.Field(alias="Corporatie")
    jaar: Series[int] = pa.Field(alias="Jaar", coerce=True)
    peildatum: Series[pd.Timestamp] = pa.Field(alias="Peildatum")

    class Config:
        strict = False
        coerce = True


class VheParamBogMogZogSchema(pa.DataFrameModel):
    """Schema for tms.market_value_parameters_vhe_param_bog_mog_zog."""

    vhe_nr: Series[str] = pa.Field(alias="VHE-nr")
    adres: Series[str] = pa.Field(alias="Adres", nullable=True)
    complexcode: Series[str] = pa.Field(alias="Complexcode", nullable=True)
    complexnaam: Series[str] = pa.Field(alias="Complexnaam", nullable=True)
    waarderingsmodel: Series[str] = pa.Field(alias="Waarderingsmodel", nullable=True)
    deelportefeuille: Series[str] = pa.Field(alias="Deelportefeuille", nullable=True)
    segment_huurregime: Series[float] = pa.Field(alias="Segment huurregime", nullable=True, coerce=True)
    classificatie: Series[str] = pa.Field(alias="Classificatie", nullable=True)
    markthuur_mh: Series[str] = pa.Field(alias="Markthuur (MH)", nullable=True)
    mh_waarde: Series[float] = pa.Field(alias="MH waarde", nullable=True, coerce=True)
    nieuw_huurcontract_nhc: Series[str] = pa.Field(alias="Nieuw huurcontract (NHC)", nullable=True)
    nhc_waarde: Series[str] = pa.Field(alias="NHC waarde", nullable=True)
    looptijd_bij_herziening_lbh: Series[str] = pa.Field(alias="Looptijd bij herziening (LBH)", nullable=True)
    lbh_waarde: Series[float] = pa.Field(alias="LBH waarde", nullable=True, coerce=True)
    mutatieleegstand_mul: Series[str] = pa.Field(alias="Mutatieleegstand (MUL)", nullable=True)
    mul_waarde: Series[float] = pa.Field(alias="MUL waarde", nullable=True, coerce=True)
    huurvrije_periode_hvp: Series[str] = pa.Field(alias="Huurvrije periode na mutatie (HVP)", nullable=True)
    hvp_waarde: Series[float] = pa.Field(alias="HVP waarde", nullable=True, coerce=True)
    huurverhogingsmoment_hvm: Series[str] = pa.Field(alias="Huurverhogingsmoment (HVM)", nullable=True)
    hvm_waarde: Series[float] = pa.Field(alias="HVM waarde", nullable=True, coerce=True)
    mutatiekosten_technisch_mkt: Series[str] = pa.Field(alias="Mutatiekosten technisch (MKT)", nullable=True)
    mkt_waarde: Series[float] = pa.Field(alias="MKT waarde", nullable=True, coerce=True)
    mutatiekosten_marketing_mkm: Series[str] = pa.Field(alias="Mutatiekosten marketing (MKM)", nullable=True)
    mkm_waarde: Series[float] = pa.Field(alias="MKM waarde", nullable=True, coerce=True)
    erfpacht_ep: Series[str] = pa.Field(alias="Erfpacht (EP)", nullable=True)
    ep_waardecorrectie: Series[float] = pa.Field(alias="EP waardecorrectie", nullable=True, coerce=True)
    ep_jaarlijks_indexeren: Series[str] = pa.Field(alias="EP jaarlijks indexeren", nullable=True)
    ep_jaar_1: Series[float] = pa.Field(alias="EP jaar 1", nullable=True, coerce=True)
    ep_jaar_2: Series[float] = pa.Field(alias="EP jaar 2", nullable=True, coerce=True)
    ep_jaar_3: Series[float] = pa.Field(alias="EP jaar 3", nullable=True, coerce=True)
    ep_jaar_4: Series[float] = pa.Field(alias="EP jaar 4", nullable=True, coerce=True)
    ep_jaar_5: Series[float] = pa.Field(alias="EP jaar 5", nullable=True, coerce=True)
    ep_jaar_6: Series[float] = pa.Field(alias="EP jaar 6", nullable=True, coerce=True)
    ep_jaar_7: Series[float] = pa.Field(alias="EP jaar 7", nullable=True, coerce=True)
    ep_jaar_8: Series[float] = pa.Field(alias="EP jaar 8", nullable=True, coerce=True)
    ep_jaar_9: Series[float] = pa.Field(alias="EP jaar 9", nullable=True, coerce=True)
    ep_jaar_10: Series[float] = pa.Field(alias="EP jaar 10", nullable=True, coerce=True)
    ep_jaar_11: Series[float] = pa.Field(alias="EP jaar 11", nullable=True, coerce=True)
    ep_jaar_12: Series[float] = pa.Field(alias="EP jaar 12", nullable=True, coerce=True)
    ep_jaar_13: Series[float] = pa.Field(alias="EP jaar 13", nullable=True, coerce=True)
    ep_jaar_14: Series[float] = pa.Field(alias="EP jaar 14", nullable=True, coerce=True)
    ep_jaar_15: Series[float] = pa.Field(alias="EP jaar 15", nullable=True, coerce=True)
    incentives_inc: Series[str] = pa.Field(alias="Incentives (INC)", nullable=True)
    inc_jaar_1: Series[float] = pa.Field(alias="INC jaar 1", nullable=True, coerce=True)
    inc_jaar_2: Series[float] = pa.Field(alias="INC jaar 2", nullable=True, coerce=True)
    inc_jaar_3: Series[float] = pa.Field(alias="INC jaar 3", nullable=True, coerce=True)
    inc_jaar_4: Series[float] = pa.Field(alias="INC jaar 4", nullable=True, coerce=True)
    inc_jaar_5: Series[float] = pa.Field(alias="INC jaar 5", nullable=True, coerce=True)
    inc_jaar_6: Series[float] = pa.Field(alias="INC jaar 6", nullable=True, coerce=True)
    inc_jaar_7: Series[float] = pa.Field(alias="INC jaar 7", nullable=True, coerce=True)
    inc_jaar_8: Series[float] = pa.Field(alias="INC jaar 8", nullable=True, coerce=True)
    inc_jaar_9: Series[float] = pa.Field(alias="INC jaar 9", nullable=True, coerce=True)
    inc_jaar_10: Series[float] = pa.Field(alias="INC jaar 10", nullable=True, coerce=True)
    inc_jaar_11: Series[float] = pa.Field(alias="INC jaar 11", nullable=True, coerce=True)
    inc_jaar_12: Series[float] = pa.Field(alias="INC jaar 12", nullable=True, coerce=True)
    inc_jaar_13: Series[float] = pa.Field(alias="INC jaar 13", nullable=True, coerce=True)
    inc_jaar_14: Series[float] = pa.Field(alias="INC jaar 14", nullable=True, coerce=True)
    inc_jaar_15: Series[float] = pa.Field(alias="INC jaar 15", nullable=True, coerce=True)
    extra_onderhoud_eo: Series[str] = pa.Field(alias="Extra onderhoud (EO)", nullable=True)
    eo_waarde: Series[float] = pa.Field(alias="EO waarde", nullable=True, coerce=True)
    huurstijging_boven_inflatie_hs: Series[str] = pa.Field(alias="Huurstijging boven inflatie (HS)", nullable=True)
    hs_waarde: Series[float] = pa.Field(alias="HS waarde", nullable=True, coerce=True)
    servicekosten_eigen_rekening_sk: Series[str] = pa.Field(alias="Servicekosten eigen rekening (SK)", nullable=True)
    sk_bedrag: Series[float] = pa.Field(alias="SK bedrag", nullable=True, coerce=True)

    corporatie: Series[str] = pa.Field(alias="Corporatie")
    jaar: Series[int] = pa.Field(alias="Jaar", coerce=True)
    peildatum: Series[pd.Timestamp] = pa.Field(alias="Peildatum")

    class Config:
        strict = False
        coerce = True


class VheParamBenaderingsmethodeSchema(pa.DataFrameModel):
    """Schema for tms.market_value_parameters_vhe_param_benaderingsmethode."""

    vhe_nr: Series[str] = pa.Field(alias="VHE-nr")
    adres: Series[str] = pa.Field(alias="Adres", nullable=True)
    complexcode: Series[str] = pa.Field(alias="Complexcode", nullable=True)
    complexnaam: Series[str] = pa.Field(alias="Complexnaam", nullable=True)
    waarderingsmodel: Series[str] = pa.Field(alias="Waarderingsmodel", nullable=True)
    deelportefeuille: Series[str] = pa.Field(alias="Deelportefeuille", nullable=True)
    segment_huurregime: Series[str] = pa.Field(alias="Segment huurregime", nullable=True)
    classificatie: Series[str] = pa.Field(alias="Classificatie", nullable=True)
    vaste_waarde_vw: Series[str] = pa.Field(alias="Vaste waarde (VW)", nullable=True)
    vw_waarde: Series[float] = pa.Field(alias="VW waarde", nullable=True, coerce=True)

    corporatie: Series[str] = pa.Field(alias="Corporatie", nullable=True, coerce=True)
    jaar: Series[int] = pa.Field(alias="Jaar", coerce=True)
    peildatum: Series[pd.Timestamp] = pa.Field(alias="Peildatum")

    class Config:
        strict = False
        coerce = True


class ComplexparamWoningenParkerenSchema(pa.DataFrameModel):
    """Schema for tms.market_value_parameters_complexparam_woningen_parkeren."""

    complexcode: Series[str] = pa.Field(alias="Complexcode")
    complexnaam: Series[str] = pa.Field(alias="Complexnaam", nullable=True)
    waarderingsmodel: Series[str] = pa.Field(alias="Waarderingsmodel", nullable=True)
    deelportefeuille: Series[str] = pa.Field(alias="Deelportefeuille", nullable=True)
    disconteringsvoet_dv: Series[str] = pa.Field(alias="Disconteringsvoet (DV)", nullable=True)
    dv_doorexploiteren: Series[float] = pa.Field(alias="DV doorexploiteren", nullable=True, coerce=True)
    dv_uitponden: Series[float] = pa.Field(alias="DV uitponden", nullable=True, coerce=True)
    exit_yield_ey: Series[str] = pa.Field(alias="Exit yield (EY)", nullable=True)
    ey_doorexploiteren: Series[float] = pa.Field(alias="EY doorexploiteren", nullable=True, coerce=True)
    ey_uitponden: Series[float] = pa.Field(alias="EY uitponden", nullable=True, coerce=True)
    scenario_sc: Series[str] = pa.Field(alias="Scenario (SC)", nullable=True)
    sc_waarde: Series[str] = pa.Field(alias="SC Waarde", nullable=True)
    onderhoud_oh: Series[str] = pa.Field(alias="Onderhoud (OH)", nullable=True)
    oh_doorexploiteren: Series[float] = pa.Field(alias="OH doorexploiteren", nullable=True, coerce=True)
    oh_uitponden: Series[float] = pa.Field(alias="OH uitponden", nullable=True, coerce=True)
    mutatieonderhoud_moh: Series[str] = pa.Field(alias="Mutatieonderhoud (MOH)", nullable=True)
    moh_doorexploiteren: Series[float] = pa.Field(alias="MOH doorexploiteren", nullable=True, coerce=True)
    moh_uitponden: Series[float] = pa.Field(alias="MOH uitponden", nullable=True, coerce=True)
    leegwaardestijging_verleden_lsv: Series[str] = pa.Field(alias="Leegwaardestijging verleden (LSV)", nullable=True)
    lsv_jaar_min1: Series[float] = pa.Field(alias="LSV jaar -1", nullable=True, coerce=True)
    lsv_jaar_0: Series[float] = pa.Field(alias="LSV jaar 0", nullable=True, coerce=True)
    leegwaardestijging_ls: Series[str] = pa.Field(alias="Leegwaardestijging (LS)", nullable=True)
    ls_jaar_1: Series[float] = pa.Field(alias="LS jaar 1", nullable=True, coerce=True)
    ls_jaar_2: Series[float] = pa.Field(alias="LS jaar 2", nullable=True, coerce=True)
    ls_jaar_3: Series[float] = pa.Field(alias="LS jaar 3", nullable=True, coerce=True)
    ls_jaar_4: Series[float] = pa.Field(alias="LS jaar 4", nullable=True, coerce=True)
    ls_jaar_5: Series[float] = pa.Field(alias="LS jaar 5", nullable=True, coerce=True)
    ls_jaar_6: Series[float] = pa.Field(alias="LS jaar 6", nullable=True, coerce=True)
    markthuurstijging_mhs: Series[str] = pa.Field(alias="Markthuurstijging boven inflatie (MHS)", nullable=True)
    mhs_jaar_1: Series[float] = pa.Field(alias="MHS jaar 1", nullable=True, coerce=True)
    mhs_jaar_2: Series[float] = pa.Field(alias="MHS jaar 2", nullable=True, coerce=True)
    mhs_jaar_3: Series[float] = pa.Field(alias="MHS jaar 3", nullable=True, coerce=True)
    mhs_jaar_4: Series[float] = pa.Field(alias="MHS jaar 4", nullable=True, coerce=True)
    mhs_jaar_5: Series[float] = pa.Field(alias="MHS jaar 5", nullable=True, coerce=True)
    mhs_jaar_6: Series[float] = pa.Field(alias="MHS jaar 6", nullable=True, coerce=True)
    mutatiegraad_doorexploiteren_md: Series[str] = pa.Field(alias="Mutatiegraad doorexploiteren (MD)", nullable=True)
    md_waarde: Series[float] = pa.Field(alias="MD waarde", nullable=True, coerce=True)
    mutatiegraad_uitponden_mu: Series[str] = pa.Field(alias="Mutatiegraad uitponden (MU)", nullable=True)
    mu_jaar_1: Series[float] = pa.Field(alias="MU jaar 1", nullable=True, coerce=True)
    mu_jaar_2: Series[float] = pa.Field(alias="MU jaar 2", nullable=True, coerce=True)
    mu_jaar_3: Series[float] = pa.Field(alias="MU jaar 3", nullable=True, coerce=True)
    mu_jaar_4: Series[float] = pa.Field(alias="MU jaar 4", nullable=True, coerce=True)
    mu_jaar_5: Series[float] = pa.Field(alias="MU jaar 5", nullable=True, coerce=True)
    mu_jaar_6: Series[float] = pa.Field(alias="MU jaar 6", nullable=True, coerce=True)
    mu_jaar_7: Series[float] = pa.Field(alias="MU jaar 7", nullable=True, coerce=True)
    mu_jaar_8: Series[float] = pa.Field(alias="MU jaar 8", nullable=True, coerce=True)
    mu_jaar_9: Series[float] = pa.Field(alias="MU jaar 9", nullable=True, coerce=True)
    mu_jaar_10: Series[float] = pa.Field(alias="MU jaar 10", nullable=True, coerce=True)
    mu_jaar_11: Series[float] = pa.Field(alias="MU jaar 11", nullable=True, coerce=True)
    mu_jaar_12: Series[float] = pa.Field(alias="MU jaar 12", nullable=True, coerce=True)
    mu_jaar_13: Series[float] = pa.Field(alias="MU jaar 13", nullable=True, coerce=True)
    mu_jaar_14: Series[float] = pa.Field(alias="MU jaar 14", nullable=True, coerce=True)
    mu_jaar_15: Series[float] = pa.Field(alias="MU jaar 15", nullable=True, coerce=True)
    gedeelte_niet_verkopen_vm: Series[str] = pa.Field(alias="Gedeelte niet verkopen bij mutatie (VM)", nullable=True)
    vm_jaar_1: Series[float] = pa.Field(alias="VM jaar 1", nullable=True, coerce=True)
    vm_jaar_2: Series[float] = pa.Field(alias="VM jaar 2", nullable=True, coerce=True)
    vm_jaar_3: Series[float] = pa.Field(alias="VM jaar 3", nullable=True, coerce=True)
    vm_jaar_4: Series[float] = pa.Field(alias="VM jaar 4", nullable=True, coerce=True)
    vm_jaar_5: Series[float] = pa.Field(alias="VM jaar 5", nullable=True, coerce=True)
    vm_jaar_6: Series[float] = pa.Field(alias="VM jaar 6", nullable=True, coerce=True)
    vm_jaar_7: Series[float] = pa.Field(alias="VM jaar 7", nullable=True, coerce=True)
    vm_jaar_8: Series[float] = pa.Field(alias="VM jaar 8", nullable=True, coerce=True)
    vm_jaar_9: Series[float] = pa.Field(alias="VM jaar 9", nullable=True, coerce=True)
    vm_jaar_10: Series[float] = pa.Field(alias="VM jaar 10", nullable=True, coerce=True)
    vm_jaar_11: Series[float] = pa.Field(alias="VM jaar 11", nullable=True, coerce=True)
    vm_jaar_12: Series[float] = pa.Field(alias="VM jaar 12", nullable=True, coerce=True)
    vm_jaar_13: Series[float] = pa.Field(alias="VM jaar 13", nullable=True, coerce=True)
    vm_jaar_14: Series[float] = pa.Field(alias="VM jaar 14", nullable=True, coerce=True)
    vm_jaar_15: Series[float] = pa.Field(alias="VM jaar 15", nullable=True, coerce=True)
    technische_splitsingskosten_ts: Series[str] = pa.Field(alias="Technische splitsingskosten (TS)", nullable=True)
    ts_waarde: Series[float] = pa.Field(alias="TS waarde", nullable=True, coerce=True)
    overige_kosten_ovk: Series[str] = pa.Field(alias="Overige kosten (OVK)", nullable=True)
    ovk_jaar_1: Series[float] = pa.Field(alias="OVK jaar 1", nullable=True, coerce=True)
    ovk_jaar_2: Series[float] = pa.Field(alias="OVK jaar 2", nullable=True, coerce=True)
    ovk_jaar_3: Series[float] = pa.Field(alias="OVK jaar 3", nullable=True, coerce=True)
    ovk_jaar_4: Series[float] = pa.Field(alias="OVK jaar 4", nullable=True, coerce=True)
    ovk_jaar_5: Series[float] = pa.Field(alias="OVK jaar 5", nullable=True, coerce=True)
    ovk_jaar_6: Series[float] = pa.Field(alias="OVK jaar 6", nullable=True, coerce=True)
    ovk_jaar_7: Series[float] = pa.Field(alias="OVK jaar 7", nullable=True, coerce=True)
    ovk_jaar_8: Series[float] = pa.Field(alias="OVK jaar 8", nullable=True, coerce=True)
    ovk_jaar_9: Series[float] = pa.Field(alias="OVK jaar 9", nullable=True, coerce=True)
    ovk_jaar_10: Series[float] = pa.Field(alias="OVK jaar 10", nullable=True, coerce=True)
    ovk_jaar_11: Series[float] = pa.Field(alias="OVK jaar 11", nullable=True, coerce=True)
    ovk_jaar_12: Series[float] = pa.Field(alias="OVK jaar 12", nullable=True, coerce=True)
    ovk_jaar_13: Series[float] = pa.Field(alias="OVK jaar 13", nullable=True, coerce=True)
    ovk_jaar_14: Series[float] = pa.Field(alias="OVK jaar 14", nullable=True, coerce=True)
    ovk_jaar_15: Series[float] = pa.Field(alias="OVK jaar 15", nullable=True, coerce=True)
    overige_opbrengsten_ovo: Series[str] = pa.Field(alias="Overige opbrengsten (OVO)", nullable=True)
    ovo_jaar_1: Series[float] = pa.Field(alias="OVO jaar 1", nullable=True, coerce=True)
    ovo_jaar_2: Series[float] = pa.Field(alias="OVO jaar 2", nullable=True, coerce=True)
    ovo_jaar_3: Series[float] = pa.Field(alias="OVO jaar 3", nullable=True, coerce=True)
    ovo_jaar_4: Series[float] = pa.Field(alias="OVO jaar 4", nullable=True, coerce=True)
    ovo_jaar_5: Series[float] = pa.Field(alias="OVO jaar 5", nullable=True, coerce=True)
    ovo_jaar_6: Series[float] = pa.Field(alias="OVO jaar 6", nullable=True, coerce=True)
    ovo_jaar_7: Series[float] = pa.Field(alias="OVO jaar 7", nullable=True, coerce=True)
    ovo_jaar_8: Series[float] = pa.Field(alias="OVO jaar 8", nullable=True, coerce=True)
    ovo_jaar_9: Series[float] = pa.Field(alias="OVO jaar 9", nullable=True, coerce=True)
    ovo_jaar_10: Series[float] = pa.Field(alias="OVO jaar 10", nullable=True, coerce=True)
    ovo_jaar_11: Series[float] = pa.Field(alias="OVO jaar 11", nullable=True, coerce=True)
    ovo_jaar_12: Series[float] = pa.Field(alias="OVO jaar 12", nullable=True, coerce=True)
    ovo_jaar_13: Series[float] = pa.Field(alias="OVO jaar 13", nullable=True, coerce=True)
    ovo_jaar_14: Series[float] = pa.Field(alias="OVO jaar 14", nullable=True, coerce=True)
    ovo_jaar_15: Series[float] = pa.Field(alias="OVO jaar 15", nullable=True, coerce=True)
    juridische_splitsingskosten_js: Series[str] = pa.Field(alias="Juridische splitsingskosten (JS)", nullable=True)
    js_waarde: Series[float] = pa.Field(alias="JS waarde", nullable=True, coerce=True)
    beheerkosten_bk: Series[str] = pa.Field(alias="Beheerkosten (BK)", nullable=True)
    bk_waarde: Series[float] = pa.Field(alias="BK waarde", nullable=True, coerce=True)
    belastingen_en_verzekeringen_bv: Series[str] = pa.Field(alias="Belastingen en verzekeringen (BV)", nullable=True)
    bv_type_invoer: Series[str] = pa.Field(alias="BV type invoer", nullable=True)
    bv_bedrag: Series[float] = pa.Field(alias="BV bedrag", nullable=True, coerce=True)
    bv_percentage: Series[float] = pa.Field(alias="BV percentage", nullable=True, coerce=True)
    ozb: Series[str] = pa.Field(alias="OZB", nullable=True)
    ozb_tarief: Series[float] = pa.Field(alias="OZB-tarief", nullable=True, coerce=True)
    huurderving_hd: Series[str] = pa.Field(alias="Huurderving (HD)", nullable=True)
    hd_waarde: Series[float] = pa.Field(alias="HD waarde", nullable=True, coerce=True)
    verkoopkosten_vk: Series[str] = pa.Field(alias="Verkoopkosten (VK)", nullable=True)
    vk_type_invoer: Series[str] = pa.Field(alias="VK type invoer", nullable=True)
    vk_bedrag: Series[float] = pa.Field(alias="VK bedrag", nullable=True, coerce=True)
    vk_percentage: Series[float] = pa.Field(alias="VK percentage", nullable=True, coerce=True)
    aanvangsleegstand_al: Series[str] = pa.Field(alias="Aanvangsleegstand (AL)", nullable=True)
    al_gereguleerd: Series[float] = pa.Field(alias="AL gereguleerd", nullable=True, coerce=True)
    al_geliberaliseerd: Series[float] = pa.Field(alias="AL geliberaliseerd", nullable=True, coerce=True)
    al_direct_uitponden: Series[str] = pa.Field(alias="AL direct uitponden", nullable=True)
    mutatieleegstand_ml: Series[str] = pa.Field(alias="Mutatieleegstand (ML)", nullable=True)
    ml_gereguleerd: Series[float] = pa.Field(alias="ML gereguleerd", nullable=True, coerce=True)
    ml_geliberaliseerd: Series[float] = pa.Field(alias="ML geliberaliseerd", nullable=True, coerce=True)

    corporatie: Series[str] = pa.Field(alias="Corporatie")
    jaar: Series[int] = pa.Field(alias="Jaar", coerce=True)
    peildatum: Series[pd.Timestamp] = pa.Field(alias="Peildatum")

    class Config:
        strict = False
        coerce = True


class ComplexparamBogMogZogSchema(pa.DataFrameModel):
    """Schema for tms.market_value_parameters_complexparam_bog_mog_zog."""

    complexcode: Series[str] = pa.Field(alias="Complexcode")
    complexnaam: Series[str] = pa.Field(alias="Complexnaam", nullable=True)
    waarderingsmodel: Series[str] = pa.Field(alias="Waarderingsmodel", nullable=True)
    deelportefeuille: Series[str] = pa.Field(alias="Deelportefeuille", nullable=True)
    disconteringsvoet_dv: Series[str] = pa.Field(alias="Disconteringsvoet (DV)", nullable=True)
    dv_waarde: Series[float] = pa.Field(alias="DV waarde", nullable=True, coerce=True)
    exit_yield_ey: Series[str] = pa.Field(alias="Exit yield (EY)", nullable=True)
    ey_waarde: Series[float] = pa.Field(alias="EY waarde", nullable=True, coerce=True)
    onderhoud_oh: Series[str] = pa.Field(alias="Onderhoud (OH)", nullable=True)
    oh_waarde: Series[float] = pa.Field(alias="OH waarde", nullable=True, coerce=True)
    markthuurstijging_mhs: Series[str] = pa.Field(alias="Markthuurstijging (MHS)", nullable=True)
    mhs_jaar_1: Series[float] = pa.Field(alias="MHS jaar 1", nullable=True, coerce=True)
    mhs_jaar_2: Series[float] = pa.Field(alias="MHS jaar 2", nullable=True, coerce=True)
    mhs_jaar_3: Series[float] = pa.Field(alias="MHS jaar 3", nullable=True, coerce=True)
    mhs_jaar_4: Series[float] = pa.Field(alias="MHS jaar 4", nullable=True, coerce=True)
    mhs_jaar_5: Series[float] = pa.Field(alias="MHS jaar 5", nullable=True, coerce=True)
    mhs_jaar_6: Series[float] = pa.Field(alias="MHS jaar 6", nullable=True, coerce=True)
    overige_kosten_ovk: Series[str] = pa.Field(alias="Overige kosten (OVK)", nullable=True)
    ovk_jaar_1: Series[float] = pa.Field(alias="OVK jaar 1", nullable=True, coerce=True)
    ovk_jaar_2: Series[float] = pa.Field(alias="OVK jaar 2", nullable=True, coerce=True)
    ovk_jaar_3: Series[float] = pa.Field(alias="OVK jaar 3", nullable=True, coerce=True)
    ovk_jaar_4: Series[float] = pa.Field(alias="OVK jaar 4", nullable=True, coerce=True)
    ovk_jaar_5: Series[float] = pa.Field(alias="OVK jaar 5", nullable=True, coerce=True)
    ovk_jaar_6: Series[float] = pa.Field(alias="OVK jaar 6", nullable=True, coerce=True)
    ovk_jaar_7: Series[float] = pa.Field(alias="OVK jaar 7", nullable=True, coerce=True)
    ovk_jaar_8: Series[float] = pa.Field(alias="OVK jaar 8", nullable=True, coerce=True)
    ovk_jaar_9: Series[float] = pa.Field(alias="OVK jaar 9", nullable=True, coerce=True)
    ovk_jaar_10: Series[float] = pa.Field(alias="OVK jaar 10", nullable=True, coerce=True)
    ovk_jaar_11: Series[float] = pa.Field(alias="OVK jaar 11", nullable=True, coerce=True)
    ovk_jaar_12: Series[float] = pa.Field(alias="OVK jaar 12", nullable=True, coerce=True)
    ovk_jaar_13: Series[float] = pa.Field(alias="OVK jaar 13", nullable=True, coerce=True)
    ovk_jaar_14: Series[float] = pa.Field(alias="OVK jaar 14", nullable=True, coerce=True)
    ovk_jaar_15: Series[float] = pa.Field(alias="OVK jaar 15", nullable=True, coerce=True)
    overige_opbrengsten_ovo: Series[str] = pa.Field(alias="Overige opbrengsten (OVO)", nullable=True)
    ovo_jaar_1: Series[float] = pa.Field(alias="OVO jaar 1", nullable=True, coerce=True)
    ovo_jaar_2: Series[float] = pa.Field(alias="OVO jaar 2", nullable=True, coerce=True)
    ovo_jaar_3: Series[float] = pa.Field(alias="OVO jaar 3", nullable=True, coerce=True)
    ovo_jaar_4: Series[float] = pa.Field(alias="OVO jaar 4", nullable=True, coerce=True)
    ovo_jaar_5: Series[float] = pa.Field(alias="OVO jaar 5", nullable=True, coerce=True)
    ovo_jaar_6: Series[float] = pa.Field(alias="OVO jaar 6", nullable=True, coerce=True)
    ovo_jaar_7: Series[float] = pa.Field(alias="OVO jaar 7", nullable=True, coerce=True)
    ovo_jaar_8: Series[float] = pa.Field(alias="OVO jaar 8", nullable=True, coerce=True)
    ovo_jaar_9: Series[float] = pa.Field(alias="OVO jaar 9", nullable=True, coerce=True)
    ovo_jaar_10: Series[float] = pa.Field(alias="OVO jaar 10", nullable=True, coerce=True)
    ovo_jaar_11: Series[float] = pa.Field(alias="OVO jaar 11", nullable=True, coerce=True)
    ovo_jaar_12: Series[float] = pa.Field(alias="OVO jaar 12", nullable=True, coerce=True)
    ovo_jaar_13: Series[float] = pa.Field(alias="OVO jaar 13", nullable=True, coerce=True)
    ovo_jaar_14: Series[float] = pa.Field(alias="OVO jaar 14", nullable=True, coerce=True)
    ovo_jaar_15: Series[float] = pa.Field(alias="OVO jaar 15", nullable=True, coerce=True)
    beheerkosten_bk: Series[str] = pa.Field(alias="Beheerkosten (BK)", nullable=True)
    bk_waarde: Series[float] = pa.Field(alias="BK waarde", nullable=True, coerce=True)
    belastingen_en_verzekeringen_bv: Series[str] = pa.Field(alias="Belastingen en verzekeringen (BV)", nullable=True)
    bv_type_invoer: Series[str] = pa.Field(alias="BV type invoer", nullable=True)
    bv_bedrag: Series[float] = pa.Field(alias="BV bedrag", nullable=True, coerce=True)
    bv_percentage: Series[float] = pa.Field(alias="BV percentage", nullable=True, coerce=True)
    ozb: Series[str] = pa.Field(alias="OZB", nullable=True)
    ozb_tarief: Series[float] = pa.Field(alias="OZB-tarief", nullable=True, coerce=True)

    corporatie: Series[str] = pa.Field(alias="Corporatie")
    jaar: Series[int] = pa.Field(alias="Jaar", coerce=True)
    peildatum: Series[pd.Timestamp] = pa.Field(alias="Peildatum")

    class Config:
        strict = False
        coerce = True
