"""Pandera schemas for policy value tables (parameters, VHE report, complex report)."""

from __future__ import annotations

import pandas as pd
import pandera.pandas as pa
from pandera.typing.pandas import Series


class PolicyValueParametersSchema(pa.DataFrameModel):
    """Schema for tms.policy_value_parameters (147 cols).

    The 60 Beleidsonderhoud + 60 EP doorexploiteren yearly columns are coerced by
    coerce_numeric_columns() in tms_report_utils.py; this schema defines key identifier
    and primary numeric columns only.
    """

    vhe_nr: Series[str] = pa.Field(alias="VHE-nr")
    adres: Series[str] = pa.Field(alias="Adres", nullable=True)
    complexcode: Series[str] = pa.Field(alias="Complexcode", nullable=True)
    complexnaam: Series[str] = pa.Field(alias="Complexnaam", nullable=True)
    waarderingsmodel: Series[str] = pa.Field(alias="Waarderingsmodel", nullable=True)
    deelportefeuille: Series[str] = pa.Field(alias="Deelportefeuille", nullable=True)
    segment_huurregime: Series[str] = pa.Field(alias="Segment huurregime", nullable=True)
    classificatie: Series[str] = pa.Field(alias="Classificatie", nullable=True)
    beleidshuur: Series[float] = pa.Field(alias="Beleidshuur", nullable=True, coerce=True)
    huurstijging_hs: Series[str] = pa.Field(alias="Huurstijging (HS)", nullable=True)
    hs_jaar_1: Series[float] = pa.Field(alias="HS jaar 1", nullable=True, coerce=True)
    hs_jaar_2: Series[float] = pa.Field(alias="HS jaar 2", nullable=True, coerce=True)
    hs_jaar_3: Series[float] = pa.Field(alias="HS jaar 3", nullable=True, coerce=True)
    hs_jaar_4: Series[float] = pa.Field(alias="HS jaar 4", nullable=True, coerce=True)
    hs_jaar_5: Series[float] = pa.Field(alias="HS jaar 5", nullable=True, coerce=True)
    hs_jaar_6_ev: Series[float] = pa.Field(alias="HS jaar 6 e.v.", nullable=True, coerce=True)
    beleidsbeheer: Series[float] = pa.Field(alias="Beleidsbeheer", nullable=True, coerce=True)
    achterstallig_onderhoud_ao: Series[str] = pa.Field(alias="Achterstallig onderhoud (AO)", nullable=True)
    ao_waarde: Series[float] = pa.Field(alias="AO waarde", nullable=True, coerce=True)
    beleidsonderhoud_bo_norm: Series[float] = pa.Field(alias="Beleidsonderhoud (BO) norm", nullable=True, coerce=True)
    beleidsonderhoud_jaar_1: Series[float] = pa.Field(alias="Beleidsonderhoud jaar 1", nullable=True, coerce=True)
    beleidsonderhoud_jaar_2: Series[float] = pa.Field(alias="Beleidsonderhoud jaar 2", nullable=True, coerce=True)
    beleidsonderhoud_jaar_3: Series[float] = pa.Field(alias="Beleidsonderhoud jaar 3", nullable=True, coerce=True)
    beleidsonderhoud_jaar_4: Series[float] = pa.Field(alias="Beleidsonderhoud jaar 4", nullable=True, coerce=True)
    beleidsonderhoud_jaar_5: Series[float] = pa.Field(alias="Beleidsonderhoud jaar 5", nullable=True, coerce=True)
    beleidsonderhoud_jaar_6: Series[float] = pa.Field(alias="Beleidsonderhoud jaar 6", nullable=True, coerce=True)
    beleidsonderhoud_jaar_7: Series[float] = pa.Field(alias="Beleidsonderhoud jaar 7", nullable=True, coerce=True)
    beleidsonderhoud_jaar_8: Series[float] = pa.Field(alias="Beleidsonderhoud jaar 8", nullable=True, coerce=True)
    beleidsonderhoud_jaar_9: Series[float] = pa.Field(alias="Beleidsonderhoud jaar 9", nullable=True, coerce=True)
    beleidsonderhoud_jaar_10: Series[float] = pa.Field(alias="Beleidsonderhoud jaar 10", nullable=True, coerce=True)
    beleidsonderhoud_jaar_11: Series[float] = pa.Field(alias="Beleidsonderhoud jaar 11", nullable=True, coerce=True)
    beleidsonderhoud_jaar_12: Series[float] = pa.Field(alias="Beleidsonderhoud jaar 12", nullable=True, coerce=True)
    beleidsonderhoud_jaar_13: Series[float] = pa.Field(alias="Beleidsonderhoud jaar 13", nullable=True, coerce=True)
    beleidsonderhoud_jaar_14: Series[float] = pa.Field(alias="Beleidsonderhoud jaar 14", nullable=True, coerce=True)
    beleidsonderhoud_jaar_15: Series[float] = pa.Field(alias="Beleidsonderhoud jaar 15", nullable=True, coerce=True)
    beleidsonderhoud_jaar_16: Series[float] = pa.Field(alias="Beleidsonderhoud jaar 16", nullable=True, coerce=True)
    beleidsonderhoud_jaar_17: Series[float] = pa.Field(alias="Beleidsonderhoud jaar 17", nullable=True, coerce=True)
    beleidsonderhoud_jaar_18: Series[float] = pa.Field(alias="Beleidsonderhoud jaar 18", nullable=True, coerce=True)
    beleidsonderhoud_jaar_19: Series[float] = pa.Field(alias="Beleidsonderhoud jaar 19", nullable=True, coerce=True)
    beleidsonderhoud_jaar_20: Series[float] = pa.Field(alias="Beleidsonderhoud jaar 20", nullable=True, coerce=True)
    beleidsonderhoud_jaar_21: Series[float] = pa.Field(alias="Beleidsonderhoud jaar 21", nullable=True, coerce=True)
    beleidsonderhoud_jaar_22: Series[float] = pa.Field(alias="Beleidsonderhoud jaar 22", nullable=True, coerce=True)
    beleidsonderhoud_jaar_23: Series[float] = pa.Field(alias="Beleidsonderhoud jaar 23", nullable=True, coerce=True)
    beleidsonderhoud_jaar_24: Series[float] = pa.Field(alias="Beleidsonderhoud jaar 24", nullable=True, coerce=True)
    beleidsonderhoud_jaar_25: Series[float] = pa.Field(alias="Beleidsonderhoud jaar 25", nullable=True, coerce=True)
    beleidsonderhoud_jaar_26: Series[float] = pa.Field(alias="Beleidsonderhoud jaar 26", nullable=True, coerce=True)
    beleidsonderhoud_jaar_27: Series[float] = pa.Field(alias="Beleidsonderhoud jaar 27", nullable=True, coerce=True)
    beleidsonderhoud_jaar_28: Series[float] = pa.Field(alias="Beleidsonderhoud jaar 28", nullable=True, coerce=True)
    beleidsonderhoud_jaar_29: Series[float] = pa.Field(alias="Beleidsonderhoud jaar 29", nullable=True, coerce=True)
    beleidsonderhoud_jaar_30: Series[float] = pa.Field(alias="Beleidsonderhoud jaar 30", nullable=True, coerce=True)
    beleidsonderhoud_jaar_31: Series[float] = pa.Field(alias="Beleidsonderhoud jaar 31", nullable=True, coerce=True)
    beleidsonderhoud_jaar_32: Series[float] = pa.Field(alias="Beleidsonderhoud jaar 32", nullable=True, coerce=True)
    beleidsonderhoud_jaar_33: Series[float] = pa.Field(alias="Beleidsonderhoud jaar 33", nullable=True, coerce=True)
    beleidsonderhoud_jaar_34: Series[float] = pa.Field(alias="Beleidsonderhoud jaar 34", nullable=True, coerce=True)
    beleidsonderhoud_jaar_35: Series[float] = pa.Field(alias="Beleidsonderhoud jaar 35", nullable=True, coerce=True)
    beleidsonderhoud_jaar_36: Series[float] = pa.Field(alias="Beleidsonderhoud jaar 36", nullable=True, coerce=True)
    beleidsonderhoud_jaar_37: Series[float] = pa.Field(alias="Beleidsonderhoud jaar 37", nullable=True, coerce=True)
    beleidsonderhoud_jaar_38: Series[float] = pa.Field(alias="Beleidsonderhoud jaar 38", nullable=True, coerce=True)
    beleidsonderhoud_jaar_39: Series[float] = pa.Field(alias="Beleidsonderhoud jaar 39", nullable=True, coerce=True)
    beleidsonderhoud_jaar_40: Series[float] = pa.Field(alias="Beleidsonderhoud jaar 40", nullable=True, coerce=True)
    beleidsonderhoud_jaar_41: Series[float] = pa.Field(alias="Beleidsonderhoud jaar 41", nullable=True, coerce=True)
    beleidsonderhoud_jaar_42: Series[float] = pa.Field(alias="Beleidsonderhoud jaar 42", nullable=True, coerce=True)
    beleidsonderhoud_jaar_43: Series[float] = pa.Field(alias="Beleidsonderhoud jaar 43", nullable=True, coerce=True)
    beleidsonderhoud_jaar_44: Series[float] = pa.Field(alias="Beleidsonderhoud jaar 44", nullable=True, coerce=True)
    beleidsonderhoud_jaar_45: Series[float] = pa.Field(alias="Beleidsonderhoud jaar 45", nullable=True, coerce=True)
    beleidsonderhoud_jaar_46: Series[float] = pa.Field(alias="Beleidsonderhoud jaar 46", nullable=True, coerce=True)
    beleidsonderhoud_jaar_47: Series[float] = pa.Field(alias="Beleidsonderhoud jaar 47", nullable=True, coerce=True)
    beleidsonderhoud_jaar_48: Series[float] = pa.Field(alias="Beleidsonderhoud jaar 48", nullable=True, coerce=True)
    beleidsonderhoud_jaar_49: Series[float] = pa.Field(alias="Beleidsonderhoud jaar 49", nullable=True, coerce=True)
    beleidsonderhoud_jaar_50: Series[float] = pa.Field(alias="Beleidsonderhoud jaar 50", nullable=True, coerce=True)
    beleidsonderhoud_jaar_51: Series[float] = pa.Field(alias="Beleidsonderhoud jaar 51", nullable=True, coerce=True)
    beleidsonderhoud_jaar_52: Series[float] = pa.Field(alias="Beleidsonderhoud jaar 52", nullable=True, coerce=True)
    beleidsonderhoud_jaar_53: Series[float] = pa.Field(alias="Beleidsonderhoud jaar 53", nullable=True, coerce=True)
    beleidsonderhoud_jaar_54: Series[float] = pa.Field(alias="Beleidsonderhoud jaar 54", nullable=True, coerce=True)
    beleidsonderhoud_jaar_55: Series[float] = pa.Field(alias="Beleidsonderhoud jaar 55", nullable=True, coerce=True)
    beleidsonderhoud_jaar_56: Series[float] = pa.Field(alias="Beleidsonderhoud jaar 56", nullable=True, coerce=True)
    beleidsonderhoud_jaar_57: Series[float] = pa.Field(alias="Beleidsonderhoud jaar 57", nullable=True, coerce=True)
    beleidsonderhoud_jaar_58: Series[float] = pa.Field(alias="Beleidsonderhoud jaar 58", nullable=True, coerce=True)
    beleidsonderhoud_jaar_59: Series[float] = pa.Field(alias="Beleidsonderhoud jaar 59", nullable=True, coerce=True)
    beleidsonderhoud_jaar_60: Series[float] = pa.Field(alias="Beleidsonderhoud jaar 60", nullable=True, coerce=True)
    erfpacht_ep: Series[str] = pa.Field(alias="Erfpacht (EP)", nullable=True)
    ep_waardecorrectie_doorexploiteren: Series[float] = pa.Field(alias="EP waardecorrectie doorexploiteren", nullable=True, coerce=True)
    ep_jaarlijks_indexeren: Series[str] = pa.Field(alias="EP jaarlijks indexeren", nullable=True)
    ep_norm: Series[float] = pa.Field(alias="EP norm", nullable=True, coerce=True)
    ep_doorexploiteren_jaar_1: Series[float] = pa.Field(alias="EP doorexploiteren jaar 1", nullable=True, coerce=True)
    ep_doorexploiteren_jaar_2: Series[float] = pa.Field(alias="EP doorexploiteren jaar 2", nullable=True, coerce=True)
    ep_doorexploiteren_jaar_3: Series[float] = pa.Field(alias="EP doorexploiteren jaar 3", nullable=True, coerce=True)
    ep_doorexploiteren_jaar_4: Series[float] = pa.Field(alias="EP doorexploiteren jaar 4", nullable=True, coerce=True)
    ep_doorexploiteren_jaar_5: Series[float] = pa.Field(alias="EP doorexploiteren jaar 5", nullable=True, coerce=True)
    ep_doorexploiteren_jaar_6: Series[float] = pa.Field(alias="EP doorexploiteren jaar 6", nullable=True, coerce=True)
    ep_doorexploiteren_jaar_7: Series[float] = pa.Field(alias="EP doorexploiteren jaar 7", nullable=True, coerce=True)
    ep_doorexploiteren_jaar_8: Series[float] = pa.Field(alias="EP doorexploiteren jaar 8", nullable=True, coerce=True)
    ep_doorexploiteren_jaar_9: Series[float] = pa.Field(alias="EP doorexploiteren jaar 9", nullable=True, coerce=True)
    ep_doorexploiteren_jaar_10: Series[float] = pa.Field(alias="EP doorexploiteren jaar 10", nullable=True, coerce=True)
    ep_doorexploiteren_jaar_11: Series[float] = pa.Field(alias="EP doorexploiteren jaar 11", nullable=True, coerce=True)
    ep_doorexploiteren_jaar_12: Series[float] = pa.Field(alias="EP doorexploiteren jaar 12", nullable=True, coerce=True)
    ep_doorexploiteren_jaar_13: Series[float] = pa.Field(alias="EP doorexploiteren jaar 13", nullable=True, coerce=True)
    ep_doorexploiteren_jaar_14: Series[float] = pa.Field(alias="EP doorexploiteren jaar 14", nullable=True, coerce=True)
    ep_doorexploiteren_jaar_15: Series[float] = pa.Field(alias="EP doorexploiteren jaar 15", nullable=True, coerce=True)
    ep_doorexploiteren_jaar_16: Series[float] = pa.Field(alias="EP doorexploiteren jaar 16", nullable=True, coerce=True)
    ep_doorexploiteren_jaar_17: Series[float] = pa.Field(alias="EP doorexploiteren jaar 17", nullable=True, coerce=True)
    ep_doorexploiteren_jaar_18: Series[float] = pa.Field(alias="EP doorexploiteren jaar 18", nullable=True, coerce=True)
    ep_doorexploiteren_jaar_19: Series[float] = pa.Field(alias="EP doorexploiteren jaar 19", nullable=True, coerce=True)
    ep_doorexploiteren_jaar_20: Series[float] = pa.Field(alias="EP doorexploiteren jaar 20", nullable=True, coerce=True)
    ep_doorexploiteren_jaar_21: Series[float] = pa.Field(alias="EP doorexploiteren jaar 21", nullable=True, coerce=True)
    ep_doorexploiteren_jaar_22: Series[float] = pa.Field(alias="EP doorexploiteren jaar 22", nullable=True, coerce=True)
    ep_doorexploiteren_jaar_23: Series[float] = pa.Field(alias="EP doorexploiteren jaar 23", nullable=True, coerce=True)
    ep_doorexploiteren_jaar_24: Series[float] = pa.Field(alias="EP doorexploiteren jaar 24", nullable=True, coerce=True)
    ep_doorexploiteren_jaar_25: Series[float] = pa.Field(alias="EP doorexploiteren jaar 25", nullable=True, coerce=True)
    ep_doorexploiteren_jaar_26: Series[float] = pa.Field(alias="EP doorexploiteren jaar 26", nullable=True, coerce=True)
    ep_doorexploiteren_jaar_27: Series[float] = pa.Field(alias="EP doorexploiteren jaar 27", nullable=True, coerce=True)
    ep_doorexploiteren_jaar_28: Series[float] = pa.Field(alias="EP doorexploiteren jaar 28", nullable=True, coerce=True)
    ep_doorexploiteren_jaar_29: Series[float] = pa.Field(alias="EP doorexploiteren jaar 29", nullable=True, coerce=True)
    ep_doorexploiteren_jaar_30: Series[float] = pa.Field(alias="EP doorexploiteren jaar 30", nullable=True, coerce=True)
    ep_doorexploiteren_jaar_31: Series[float] = pa.Field(alias="EP doorexploiteren jaar 31", nullable=True, coerce=True)
    ep_doorexploiteren_jaar_32: Series[float] = pa.Field(alias="EP doorexploiteren jaar 32", nullable=True, coerce=True)
    ep_doorexploiteren_jaar_33: Series[float] = pa.Field(alias="EP doorexploiteren jaar 33", nullable=True, coerce=True)
    ep_doorexploiteren_jaar_34: Series[float] = pa.Field(alias="EP doorexploiteren jaar 34", nullable=True, coerce=True)
    ep_doorexploiteren_jaar_35: Series[float] = pa.Field(alias="EP doorexploiteren jaar 35", nullable=True, coerce=True)
    ep_doorexploiteren_jaar_36: Series[float] = pa.Field(alias="EP doorexploiteren jaar 36", nullable=True, coerce=True)
    ep_doorexploiteren_jaar_37: Series[float] = pa.Field(alias="EP doorexploiteren jaar 37", nullable=True, coerce=True)
    ep_doorexploiteren_jaar_38: Series[float] = pa.Field(alias="EP doorexploiteren jaar 38", nullable=True, coerce=True)
    ep_doorexploiteren_jaar_39: Series[float] = pa.Field(alias="EP doorexploiteren jaar 39", nullable=True, coerce=True)
    ep_doorexploiteren_jaar_40: Series[float] = pa.Field(alias="EP doorexploiteren jaar 40", nullable=True, coerce=True)
    ep_doorexploiteren_jaar_41: Series[float] = pa.Field(alias="EP doorexploiteren jaar 41", nullable=True, coerce=True)
    ep_doorexploiteren_jaar_42: Series[float] = pa.Field(alias="EP doorexploiteren jaar 42", nullable=True, coerce=True)
    ep_doorexploiteren_jaar_43: Series[float] = pa.Field(alias="EP doorexploiteren jaar 43", nullable=True, coerce=True)
    ep_doorexploiteren_jaar_44: Series[float] = pa.Field(alias="EP doorexploiteren jaar 44", nullable=True, coerce=True)
    ep_doorexploiteren_jaar_45: Series[float] = pa.Field(alias="EP doorexploiteren jaar 45", nullable=True, coerce=True)
    ep_doorexploiteren_jaar_46: Series[float] = pa.Field(alias="EP doorexploiteren jaar 46", nullable=True, coerce=True)
    ep_doorexploiteren_jaar_47: Series[float] = pa.Field(alias="EP doorexploiteren jaar 47", nullable=True, coerce=True)
    ep_doorexploiteren_jaar_48: Series[float] = pa.Field(alias="EP doorexploiteren jaar 48", nullable=True, coerce=True)
    ep_doorexploiteren_jaar_49: Series[float] = pa.Field(alias="EP doorexploiteren jaar 49", nullable=True, coerce=True)
    ep_doorexploiteren_jaar_50: Series[float] = pa.Field(alias="EP doorexploiteren jaar 50", nullable=True, coerce=True)
    ep_doorexploiteren_jaar_51: Series[float] = pa.Field(alias="EP doorexploiteren jaar 51", nullable=True, coerce=True)
    ep_doorexploiteren_jaar_52: Series[float] = pa.Field(alias="EP doorexploiteren jaar 52", nullable=True, coerce=True)
    ep_doorexploiteren_jaar_53: Series[float] = pa.Field(alias="EP doorexploiteren jaar 53", nullable=True, coerce=True)
    ep_doorexploiteren_jaar_54: Series[float] = pa.Field(alias="EP doorexploiteren jaar 54", nullable=True, coerce=True)
    ep_doorexploiteren_jaar_55: Series[float] = pa.Field(alias="EP doorexploiteren jaar 55", nullable=True, coerce=True)
    ep_doorexploiteren_jaar_56: Series[float] = pa.Field(alias="EP doorexploiteren jaar 56", nullable=True, coerce=True)
    ep_doorexploiteren_jaar_57: Series[float] = pa.Field(alias="EP doorexploiteren jaar 57", nullable=True, coerce=True)
    ep_doorexploiteren_jaar_58: Series[float] = pa.Field(alias="EP doorexploiteren jaar 58", nullable=True, coerce=True)
    ep_doorexploiteren_jaar_59: Series[float] = pa.Field(alias="EP doorexploiteren jaar 59", nullable=True, coerce=True)
    ep_doorexploiteren_jaar_60: Series[float] = pa.Field(alias="EP doorexploiteren jaar 60", nullable=True, coerce=True)

    corporatie: Series[str] = pa.Field(alias="Corporatie")
    jaar: Series[int] = pa.Field(alias="Jaar", coerce=True)
    peildatum: Series[pd.Timestamp] = pa.Field(alias="Peildatum")

    class Config:
        strict = False
        coerce = True


class PolicyValueReportVheSchema(pa.DataFrameModel):
    """Schema for tms.policy_value_report_vhe (36 cols)."""

    vhe_nr: Series[str] = pa.Field(alias="VHE-nr")
    waarderingscomplex: Series[str] = pa.Field(alias="Waarderingscomplex", nullable=True)
    complexnaam: Series[str] = pa.Field(alias="Complexnaam", nullable=True)
    deelportefeuille: Series[str] = pa.Field(alias="Deelportefeuille", nullable=True)
    adres: Series[str] = pa.Field(alias="Adres", nullable=True)
    postcode: Series[str] = pa.Field(alias="Postcode", nullable=True)
    scenario: Series[str] = pa.Field(alias="Scenario", nullable=True)
    model: Series[str] = pa.Field(alias="Model", nullable=True)
    bouwjaar: Series[float] = pa.Field(alias="Bouwjaar", nullable=True, coerce=True)
    handboektype: Series[str] = pa.Field(alias="Handboektype", nullable=True)
    classificatie: Series[str] = pa.Field(alias="Classificatie", nullable=True)
    marktwaarde: Series[float] = pa.Field(alias="Marktwaarde", nullable=True, coerce=True)
    beschikbaarheid_scenario: Series[float] = pa.Field(alias="Beschikbaarheid (scenario)", nullable=True, coerce=True)
    beschikbaarheid_eindwaarde: Series[float] = pa.Field(alias="Beschikbaarheid (eindwaarde)", nullable=True, coerce=True)
    beschikbaarheid_60_jaar: Series[float] = pa.Field(alias="Beschikbaarheid (60 jaar)", nullable=True, coerce=True)
    beschikbaarheid_overdrachtskosten: Series[float] = pa.Field(alias="Beschikbaarheid (overdrachtskosten)", nullable=True, coerce=True)
    betaalbaarheid: Series[float] = pa.Field(alias="Betaalbaarheid", nullable=True, coerce=True)
    kwaliteit_onderhoud: Series[float] = pa.Field(alias="Kwaliteit (onderhoud)", nullable=True, coerce=True)
    kwaliteit_efg_labels: Series[float] = pa.Field(alias="Kwaliteit (EFG-labels)", nullable=True, coerce=True)
    beheer: Series[float] = pa.Field(alias="Beheer", nullable=True, coerce=True)
    disconteringsvoet: Series[float] = pa.Field(alias="Disconteringsvoet", nullable=True, coerce=True)
    beleidswaarde: Series[float] = pa.Field(alias="Beleidswaarde", nullable=True, coerce=True)
    beleidswaarde_marktwaarde: Series[float] = pa.Field(alias="Beleidswaarde / Marktwaarde", nullable=True, coerce=True)
    beleidshuur: Series[float] = pa.Field(alias="Beleidshuur", nullable=True, coerce=True)
    beleidsonderhoud_norm: Series[float] = pa.Field(alias="Beleidsonderhoud (norm)", nullable=True, coerce=True)
    beleidsbeheer: Series[float] = pa.Field(alias="Beleidsbeheer", nullable=True, coerce=True)
    methode_reg_huurstijging_blw: Series[str] = pa.Field(alias="Methode reg. huurstijging boven infl. blw", nullable=True)
    reg_huurstijging_blw_jaar_1: Series[float] = pa.Field(alias="Reg. huurstijging boven infl. blw jaar 1", nullable=True, coerce=True)
    reg_huurstijging_blw_jaar_2: Series[float] = pa.Field(alias="Reg. huurstijging boven infl. blw jaar 2", nullable=True, coerce=True)
    reg_huurstijging_blw_jaar_3: Series[float] = pa.Field(alias="Reg. huurstijging boven infl. blw jaar 3", nullable=True, coerce=True)
    reg_huurstijging_blw_jaar_4: Series[float] = pa.Field(alias="Reg. huurstijging boven infl. blw jaar 4", nullable=True, coerce=True)
    reg_huurstijging_blw_jaar_5: Series[float] = pa.Field(alias="Reg. huurstijging boven infl. blw jaar 5", nullable=True, coerce=True)
    reg_huurstijging_blw_jaar_6: Series[float] = pa.Field(alias="Reg. huurstijging boven infl. blw jaar 6", nullable=True, coerce=True)

    corporatie: Series[str] = pa.Field(alias="Corporatie")
    jaar: Series[int] = pa.Field(alias="Jaar", coerce=True)
    peildatum: Series[pd.Timestamp] = pa.Field(alias="Peildatum")

    class Config:
        strict = False
        coerce = True


class PolicyValueReportComplexSchema(pa.DataFrameModel):
    """Schema for tms.policy_value_report_complex (35 cols)."""

    waarderingscomplex: Series[str] = pa.Field(alias="Waarderingscomplex")
    complexnaam: Series[str] = pa.Field(alias="Complexnaam", nullable=True)
    deelportefeuille: Series[str] = pa.Field(alias="Deelportefeuille", nullable=True)
    straatnaam: Series[str] = pa.Field(alias="Straatnaam", nullable=True)
    scenario: Series[str] = pa.Field(alias="Scenario", nullable=True)
    model: Series[str] = pa.Field(alias="Model", nullable=True)
    aantal_vhes: Series[float] = pa.Field(alias="Aantal VHE's", nullable=True, coerce=True)
    aantal_vhes_leegstaand: Series[float] = pa.Field(alias="Aantal VHE's leegstaand", nullable=True, coerce=True)
    percentage_leegstaand: Series[float] = pa.Field(alias="Percentage leegstaand in complex", nullable=True, coerce=True)
    marktwaarde: Series[float] = pa.Field(alias="Marktwaarde", nullable=True, coerce=True)
    beschikbaarheid_scenario: Series[float] = pa.Field(alias="Beschikbaarheid (scenario)", nullable=True, coerce=True)
    beschikbaarheid_eindwaarde: Series[float] = pa.Field(alias="Beschikbaarheid (eindwaarde)", nullable=True, coerce=True)
    beschikbaarheid_60_jaar: Series[float] = pa.Field(alias="Beschikbaarheid (60 jaar)", nullable=True, coerce=True)
    beschikbaarheid_overdrachtskosten: Series[float] = pa.Field(alias="Beschikbaarheid (overdrachtskosten)", nullable=True, coerce=True)
    betaalbaarheid: Series[float] = pa.Field(alias="Betaalbaarheid", nullable=True, coerce=True)
    kwaliteit_onderhoud: Series[float] = pa.Field(alias="Kwaliteit (onderhoud)", nullable=True, coerce=True)
    kwaliteit_efg_labels: Series[float] = pa.Field(alias="Kwaliteit (EFG-labels)", nullable=True, coerce=True)
    beheer: Series[float] = pa.Field(alias="Beheer", nullable=True, coerce=True)
    disconteringsvoet: Series[float] = pa.Field(alias="Disconteringsvoet", nullable=True, coerce=True)
    beleidswaarde: Series[float] = pa.Field(alias="Beleidswaarde", nullable=True, coerce=True)
    beleidswaarde_per_vhe: Series[float] = pa.Field(alias="Beleidswaarde per VHE", nullable=True, coerce=True)
    beleidswaarde_marktwaarde: Series[float] = pa.Field(alias="Beleidswaarde / Marktwaarde", nullable=True, coerce=True)
    beleidshuur_per_vhe: Series[float] = pa.Field(alias="Beleidshuur per VHE", nullable=True, coerce=True)
    beleidsonderhoud_per_vhe_norm: Series[float] = pa.Field(alias="Beleidsonderhoud per VHE (norm)", nullable=True, coerce=True)
    beleidsbeheer_per_vhe: Series[float] = pa.Field(alias="Beleidsbeheer per VHE", nullable=True, coerce=True)
    methode_reg_huurstijging_blw: Series[str] = pa.Field(alias="Methode reg. huurstijging boven infl. blw", nullable=True)
    reg_huurstijging_blw_jaar_1: Series[float] = pa.Field(alias="Reg. huurstijging boven infl. blw jaar 1", nullable=True, coerce=True)
    reg_huurstijging_blw_jaar_2: Series[float] = pa.Field(alias="Reg. huurstijging boven infl. blw jaar 2", nullable=True, coerce=True)
    reg_huurstijging_blw_jaar_3: Series[float] = pa.Field(alias="Reg. huurstijging boven infl. blw jaar 3", nullable=True, coerce=True)
    reg_huurstijging_blw_jaar_4: Series[float] = pa.Field(alias="Reg. huurstijging boven infl. blw jaar 4", nullable=True, coerce=True)
    reg_huurstijging_blw_jaar_5: Series[float] = pa.Field(alias="Reg. huurstijging boven infl. blw jaar 5", nullable=True, coerce=True)
    reg_huurstijging_blw_jaar_6: Series[float] = pa.Field(alias="Reg. huurstijging boven infl. blw jaar 6", nullable=True, coerce=True)

    corporatie: Series[str] = pa.Field(alias="Corporatie")
    jaar: Series[int] = pa.Field(alias="Jaar", coerce=True)
    peildatum: Series[pd.Timestamp] = pa.Field(alias="Peildatum")

    class Config:
        strict = False
        coerce = True
