"""Company partitions for the Marktpresentatie pipeline.

This module owns both the canonical list of included housing corporations and
the shared Dagster partition definition used across the company-partitioned
TMS and VGR asset layers.

To add or remove a corporation, edit ``INCLUDED_COMPANIES`` and restart
Dagster. Company names must match the TMS API's company identifiers exactly.
"""

import dagster as dg

INCLUDED_COMPANIES: list[str] = [
    "3B Wonen",
    # "Aansluiting Stadgenoot",  # Not in legacy 2025
    "Acantus",
    "Accolade",
    "Actium",
    "Alwel",
    "Antares",
    "Antonius van Padua",
    "Arcade",
    "BWHippo",
    "Baston Wonen",
    "Bazalt Wonen",
    "Berg & Terblijt",
    # "Berg En Terblijt",  # Not in legacy 2025 (duplicate of Berg & Terblijt)
    "Beter Wonen Almelo",
    "Beveland Wonen",
    "Bo-Ex",
    "BrabantWonen",
    "Brederode",
    "Casade",
    "CazasWonen",
    "Centrada",
    "Charlotte van Beuningen",
    "Clavis",
    "Compaen",
    "DUWO",
    "De Goede Woning Apeldoorn",
    "De Goede Woning Rijssen",
    "De Huismeesters",
    "De Key",
    "De Leeuw van Putten",
    "De Sleutels",
    "De Woningraat",
    "De Woningstichting Wageningen",
    "De Woonmensen",
    "De Woonplaats",
    "DeVolmacht",
    "DeWoonschakel",
    "DeZaligheden",
    "DeltaWonen",
    "Domesta",
    "Domijn",
    "Dudok Wonen",
    "Dunavie",
    "Dynhus",
    "EelderWB",
    # "Eigenhaard",  # Not in legacy 2025
    "Elan Wonen",
    "Elkien",
    "Fien",
    "Goed Wonen Gemert",
    "GoedWonen",
    "Goud Wonen",
    "GroenWonen",
    "Groninger Huis",
    "Grootslag",
    "HEEMwonen",
    "HW Wonen",
    "Haag Wonen",
    "Habion",
    "Havensteder",
    "HefWonen",
    "Het Gooi en Omstreken",
    "HofWonen",
    "Huis & Hof",
    "Idealis",
    "Intermaris",
    "JOOST",
    "Kennemer Wonen",
    "KleurrijkWonen",
    "KrijtlandWonen",
    "L'escaut woonservice",
    "LEKSTEDEwonen",
    "Laurentius",
    "Lefier",
    "Leystromen",
    "MaasWonen",
    "Maasdelta",
    "Maasvallei",
    "Mercatus",
    "Mijande Wonen",
    "Mooiland",
    "Mozaiek Wonen",
    "NabijWonen",
    "Nester",
    "Nijestee",
    "Omnia Wonen",
    "Ons Doel",
    "Ons Huis Apeldoorn",
    "Ons Huis Enschede",
    "Parteon",
    "PatrimoniumB",
    "PeelrandWonen",
    "Plavei",
    "Poort6",
    "Portaal",
    "Pre Wonen",
    "ProWonen",
    "Rentree",
    "Ressort Wonen",
    "Rhenam Wonen",
    "Rijswijk Wonen",
    "Rochdale",
    "Rondom Wonen",
    "Rosehaghe",
    "SJHT",
    "SOR",
    "SSH",
    "SSHN",
    "SWZ",
    "SallandWonen",
    "Samenwerking Slikkerveer",
    "Servatius",
    "Sint Joseph Almelo",
    "SiteWoondiensten",
    "StWillibrordus",
    "Stadgenoot",
    "Stadlander",
    "Staedion",
    "Stedelink",
    "Stek",
    "TBV Wonen",
    "TIWOS",
    "Tablis Wonen",
    "Talis",
    "Thius",
    "Thuisvester",
    "Triada",
    "Trivire",
    "Trudo",
    "Uwoon",
    # "VGZ (Habion)",  # Not in legacy 2025
    "VanhierWonen",
    "Vecht en Omstreken",
    "Vechtdal Wonen",
    "Vechthorst",
    "Veenvesters",
    "Velison Wonen",
    "Veluwonen",
    "Vidomes",
    "Vincio Wonen",
    "Vivare",
    "Viverion",
    # "Viveste",  # Not in legacy 2025
    "Volkshuisvesting Arnhem",
    # "VOF Amaris de Veste (Habion)",  # Not in legacy 2025
    "WBO wonen",
    "WVH",
    "Waardwonen",
    "Wassenaarsche Bouwstichting",
    "Waterweg Wonen",
    "Wbv Maarn",
    "WelWonen",
    "Welbions",
    "Weller",
    "Wierden en Borgen",
    "WoCom",
    "Woensdrecht",
    "Wold en Waard",
    "Wonen Limburg",
    "Wonen Meerssen",
    "Wonen Zuid",
    "WonenBreburg",
    "WonenWittem",
    "Woningbedrijf Velsen",
    "Woningbelang",
    "Woningbouwvereniging Gelderland",
    "Woningstichting Anna Paulowna",
    "Woningstichting Barneveld",
    "Woningstichting Den Helder",
    "Woningstichting Nieuwkoop",
    "Woningstichting Samenwerking",
    "Woningstichting Tubbergen",
    # "Wonion",  # Not in legacy 2025
    "WoonInvest",
    "Woonbedrijf Ieder1",
    "Woonbedrijf SWS.Hhvl",
    "Woonborg",
    "Woonbron",
    "Wooncompagnie",
    # "Wooncompas",  # Not in legacy 2025
    "Woonconcept",
    "Woonforte",
    "Woongoed Middelburg",
    "Woongoed Zeeuws Vlaanderen",
    "Woongroen",
    "Woonik",
    "Woonin",
    "Wooninc.",
    "Woonkracht10",
    "Woonkwartier",
    "Woonmeij",
    "Woonpartners",
    "Woonpartners Midden Holland",
    "Woonplus Schiedam",
    "Woonpunt",
    "Woonservice Drenthe",
    "Woonstede",
    # "Woonstede aansluiting",  # Not in legacy 2025
    "Woonstichting 'thuis",
    "Woonstichting Hulst",
    "Woonveste",
    "Woonvizier",
    "Woonwaard",
    "Woonwaarts",
    "Woonwenz",
    # "Woonzorg Nederland",  # Not in legacy 2025
    "Wormerwonen",
    "WsWeststellingwerf",
    "ZOwonen",
    "ZVH",
    "Zaam Wonen",
    "Zayaz",
    "Zeeuwland",
]

company_partitions = dg.StaticPartitionsDefinition(INCLUDED_COMPANIES)
BACKFILL_POLICY = dg.BackfillPolicy.multi_run(max_partitions_per_run=1)


def get_company_partition_keys(context: dg.AssetExecutionContext) -> list[str]:
    """Return requested company partitions in canonical partition order."""
    requested = set(context.partition_keys)
    return [company for company in INCLUDED_COMPANIES if company in requested]
